name: 'Build and Deploy Terraform'

on:
  push:
    branches: [ "dev" ]
  pull_request:

defaults:
  run:
    working-directory: infra

jobs:
  build_and_deploy:
    name: 'Build and Deploy'
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package
        working-directory: .

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ROOT_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ROOT_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Format
        run: terraform fmt -recursive -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false \
          -var="jar_file_path=../target/untitled-1.0-SNAPSHOT.jar"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false -var="jar_file_path=../target/untitled-1.0-SNAPSHOT.jar"
